#+latex_header: \hypersetup{colorlinks=true, linkcolor=black}
#+TITLE: Automatyczne fakturowanie dokumentów WZ.

* Cel
  
  Zautomatyzowanie wystawnia dokumentów fakturowych w celu ułatwienia i przyspieszenia pracy osób fakturujących.
  
* Schemat działania
  
  Magazynier po skompletowaniu towaru zamyka WZ. Skrypt co 15 minut iteruje przez zamknięte dokumenty WZ, sprawdza czy
  dokument został już zafakturowany. Jeżeli tak to go pomija jeżeli nie to generuje otwarty dokument FV.  Jeżeli dzień
  wywołania skryptu jest ostatnim dniem miesiąca to skrypt iteruje również przez otwarte dokumenty WZ, sprawdza czy
  dokument został już zafakturowany. Jeżeli tak to go pomija, jeżeli nie to generuje otwarty dokument FV.

* Specyfikacja techniczna
#+OPTIONS: ^:{}
  
  - cyklicznośc uruchomienia: 15 min.
  - miejsce uruchomienia: serwer z windows / lub dowolny serwer z instalacją Python3
  - wymagane biblioteki: requests, asgard_api

* Do zrobienia: :noexport: [6/9]
** DONE Skrypt do fakturowania WZ

   Dopisać do nowego api skrypt do fakturowania WZ
   [[file:specyfikacja_techniczna.org][Specyfikacja techniczna skryptu
]]
** DONE Stan WZ
 
   Poszukać sposobu na zdefiniowanie czy WZ posiada FV
   
   [#]Jeżeli dokument WZ posiada FV to nie może zostać ponownie zafakturowany.
   Api zwraca odpowiedź z kodem 500, oraz informacją że dokument nie może być 
   zafakturowany.

** DONE EURONIP

   Jak przeprowadzić sprawdzanie EURONIPU przy przed wygenerowaniem FV
   [info] Fakturzystki sprawdzają EURONIP na FV
   [?] Dlaczego EURONIP sprawdzany jest na samym końcu zamówienia zamiast na ZO, 
   przed rozpoczęciem zlecenia.

** DONE Podwóje fakturowanie WZ

   Czy można ponownie zafakturować zafakturowany dokument WZ

   [#] Nie można zafakturować dokumentu który posiada fakturę.
   Api zwraca odpowiedź z kodem 500, oraz informacją że dokument nie może być
   zafakturowany.

** TODO Edycja otwartej FV przez dwie osoby jednocześnie

   Sprawdzić jak zachowa się system gdy dwie osoby będą edytowały otwarty dokumentu FV

** DONE Ostatni dzień miesiąca

   Na koniec miesiąca faktury muszę zostać wystawione do otwartych dokumentów WZ

** DONE Problem jedej FV do wielu WZ

   Rozwiązać problem sytuacji gdy klient z chce jedną fakturę do wielu WZ. Wg schematu system wystawi tyle faktur ile ma
   WZ.
   [#] Takie FV będą wystawiane ręcznie.

** TODO Wartości dowolne na FV

   Na FV muszę być utworzone wartości dowolne z których osoby fakturujące korzystają przy generowaniu FV z WZ.

** TODO Cron 15 min

   Skrypt wykonywać się będzie co 15 min.
   
